version: "3.7"

services:
  tailscale-caddy:
    image: tailscale/tailscale:latest
    hostname: tailscale-nginx
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${TAILSCALE_STATE_PATH}:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    volumes:
      - ${PWD}:/etc/caddy/Caddyfile
      - ${CADDY_DATA_PATH}:/data # Optional
      - ${CADDY_CONFIG_PATH}:/config # Optional
    depends_on:
      - tailscale-caddy
    network_mode: service:tailscale-caddy
